# Generated by Django 2.0.2 on 2018-04-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180419_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteuser',
            name='invite_no',
            field=models.CharField(default='tYql0eb', max_length=50),
        ),
    ]
