# Generated by Django 2.0.2 on 2018-04-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180419_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteuser',
            name='invite_no',
            field=models.CharField(default='LL5kJ2R', max_length=50),
        ),
    ]
