# Generated by Django 2.0.2 on 2018-04-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180419_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteuser',
            name='invite_no',
            field=models.CharField(default='015aff1', max_length=50),
        ),
    ]
