# Generated by Django 2.0.2 on 2018-04-23 12:15

import common.common_fun
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180423_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inviteuser',
            name='invite_no',
            field=models.CharField(default=common.common_fun.GenerateAlphaNum, max_length=50),
        ),
    ]
