# Generated by Django 2.0.2 on 2018-05-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20180508_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mailchimp_id',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
