# Generated by Django 2.0.2 on 2018-09-26 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_user_mailchimp_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('user_id', models.DecimalField(decimal_places=0, default=1, max_digits=10)),
                ('status', models.CharField(default='No Pre-order', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
