# Generated by Django 2.0.2 on 2018-09-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_preorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='status',
            field=models.CharField(default='No Pre-order', max_length=256, null=True),
        ),
    ]
