# Generated by Django 2.0.2 on 2018-09-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20180926_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='user_id',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
