# Generated by Django 2.0.2 on 2018-09-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20180926_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(default='Lead', max_length=256),
        ),
    ]
