# Generated by Django 2.0.2 on 2018-04-19 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lawn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('address', models.TextField()),
                ('is_delete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_Lawn', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LawnAnalytic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LawnInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('initial_lot_size', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('initial_lawn_area', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('initial_lawn_size', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('observed_lawn_size', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('observed_shaded_lawn', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('observed_visibility', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('observed_shade', models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True)),
                ('grass_zone', models.CharField(max_length=200, null=True)),
                ('observed_grass_type', models.CharField(max_length=100)),
                ('lawn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawn_Info', to='lawn.Lawn')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SelectedQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='option_SQO', to='faq.Option')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_SQO', to='faq.Questionnaire')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserQuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('is_delete', models.BooleanField(default=False)),
                ('lawn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lawn_UQO', to='lawn.Lawn')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_UQO', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='selectedquestionoption',
            name='user_question_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UserQuestionOption_SQO', to='lawn.UserQuestionOption'),
        ),
    ]
