# Generated by Django 2.0.2 on 2018-05-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawn',
            name='basement',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lawn',
            name='number_of_floors',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lawn',
            name='yearbuilt',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lawn',
            name='zestimate',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
