# Generated by Django 2.0.2 on 2018-05-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawn', '0003_lawn_finished_square_footage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawn',
            name='Estimated_Lawn_Size',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
