# Generated by Django 2.0.2 on 2018-05-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawn', '0004_lawn_estimated_lawn_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawn',
            old_name='Estimated_Lawn_Size',
            new_name='estimated_lawn_size',
        ),
    ]
