# Generated by Django 2.0.2 on 2018-09-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawn', '0005_auto_20180518_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawn',
            name='manual_review_right',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lawn',
            name='manual_review_wrong',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='lawn',
            name='tennis_court_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
