# Generated by Django 2.0.2 on 2018-09-07 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawn', '0006_auto_20180906_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawn',
            name='is_manual_review',
            field=models.BooleanField(default=False),
        ),
    ]
