# Generated by Django 2.0.2 on 2018-09-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawn', '0007_lawn_is_manual_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawn',
            name='is_manual_review',
        ),
        migrations.RemoveField(
            model_name='lawn',
            name='manual_review_right',
        ),
        migrations.RemoveField(
            model_name='lawn',
            name='manual_review_wrong',
        ),
        migrations.AddField(
            model_name='lawn',
            name='is_right_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawn',
            name='is_wrong_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawn',
            name='manual_review',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
