# Generated by Django 2.0.2 on 2018-09-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawn', '0008_auto_20180907_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawn',
            name='manual_review',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
