# Generated by Django 2.0.2 on 2018-09-26 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawn', '0010_lawn_send_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawn',
            name='image',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
