# Generated by Django 2.0.2 on 2018-09-27 06:21

import common.common_fun
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawn', '0011_lawn_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawn',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=common.common_fun.lawn_image_upload),
        ),
    ]
