# Generated by Django 2.0.2 on 2018-10-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawn', '0012_auto_20180927_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawn',
            name='administrative_area_level_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lawn',
            name='country',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lawn',
            name='lat',
            field=models.DecimalField(decimal_places=32, default=0, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='lawn',
            name='lng',
            field=models.DecimalField(decimal_places=32, default=0, max_digits=32, null=True),
        ),
        migrations.AddField(
            model_name='lawn',
            name='locality',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lawn',
            name='postal_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lawn',
            name='route',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lawn',
            name='street_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
