# Generated by Django 2.0.2 on 2018-10-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawn', '0014_auto_20181003_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawn',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lawn',
            name='lat',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='lawn',
            name='lng',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='lawn',
            name='postal_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
