# Generated by Django 2.0.2 on 2018-10-05 09:27

import common.common_fun
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lawn', '0015_auto_20181003_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawnImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated at')),
                ('lawn_id', models.IntegerField(default=0, max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to=common.common_fun.lawn_image_upload)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='lawn',
            name='image',
        ),
    ]
