# Generated by Django 2.0.2 on 2018-10-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawn', '0016_auto_20181005_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawnimage',
            name='lawn_id',
            field=models.IntegerField(default=0),
        ),
    ]
