# Generated by Django 2.0.2 on 2018-10-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lawn', '0017_auto_20181005_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawnimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lawnimage',
            name='updated_at',
        ),
    ]
